Relax grpc-js version constraint in fabric-shim (#437)
When different versions of @grpc/grpc-js are resolved in the dependency
tree, the following error in the chaincode can prevent the chaincode
container from starting:

    TypeError: Channel credentials must be a ChannelCredentials object

This is typically caused by a mismatch between the versions of
@grpc/grpc-js specified by fabric-shim and @hyperledger/fabric-protos.
Provided the version constraints are loose enough to allow a single
version to satisfy both dependencies, the mismatch can be avoided by
deduping dependencies in a consuming chaincode.

This change relaxes the @grpc/grpc-js version constraint in fabric-shim
to allow compatibility with any newer minor release version specified by
@hyperledger/fabric-protos.

Signed-off-by: Mark S. Lewis <Mark.S.Lewis@outlook.com>